# Set the base image to Ubuntu
FROM ubuntu

# File Author / Maintainer
MAINTAINER Rene

# Install Letsencrypt
RUN apt-get update && apt-get install -y letsencrypt

# Set default command run bash.
CMD ["/bin/bash"]