# Based on Ubuntu
############################################################

# Set the base image to Ubuntu
FROM ubuntu

# File Author / Maintainer
MAINTAINER Rene


# Install standard tools all batt use them for now.
RUN apt-get update && apt-get install -y nano curl dialog net-tools

CMD ["/bin/bash"]